[workspace]
members = ["packages/cli", "packages/editor", "packages/model", "packages/renderer"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/ScarletFlash/beatgraph"
rust-version = "1.91"

[workspace.dependencies]
wasm-bindgen = "0.2"

[workspace.metadata]
name = "beatgraph-rust"
